# Definición de la API y versión utilizada
apiVersion: v1

# Especifica que este archivo describe un objeto de tipo PersistentVolume
kind: PersistentVolume

# Metadatos asociados al PersistentVolume
metadata:
  # Nombre del PersistentVolume
  name: postgres-pv

# Especificaciones del PersistentVolume
spec:
  # Capacidad de almacenamiento del volumen
  capacity:
    # Espacio de almacenamiento disponible en el volumen
    storage: 2Gi # 2 Gigabytes de almacenamiento

  # Modo del volumen
  volumeMode: Filesystem # El volumen se montará como un sistema de archivos

  # Clase de almacenamiento utilizada
  storageClassName: standard

  # Modos de acceso permitidos para el volumen
  accessModes:
    - ReadWriteOnce # El volumen puede ser montado en lectura/escritura por un único nodo

  # Fuente del volumen
  hostPath:
    # Ruta en el sistema de archivos del host donde se almacenarán los datos
    path: /var/lib/postgresql/data

    # Tipo de hostPath, crea el directorio si no existe
    type: DirectoryOrCreate
