apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubernetes-nodes
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      k8s-app: kubelet
  endpoints:
    - port: https-metrics
  namespaceSelector:
    matchNames:
      - kube-system
