apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: msvc-usuarios-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: msvc-usuarios
  endpoints:
    - port: http # Ajustar si es necesario
      path: /actuator/prometheus
  namespaceSelector:
    matchNames:
      - default # Cambia esto si `msvc-usuarios` está en otro namespace
