apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: msvc-cursos-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: msvc-cursos
  endpoints:
    - port: http-trafic-cursos # Asegúrate de que coincida con el nombre del puerto en el Service
      path: /actuator/prometheus
  namespaceSelector:
    matchNames:
      - default # Cambia esto si `msvc-cursos` está en otro namespace
