CREATE TABLE IF NOT EXISTS cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cursos_usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT UNIQUE,
    curso_id BIGINT REFERENCES cursos(id),
    PRIMARY KEY (id)
);

-- Índice para optimizar findByCursoId en la tabla cursos_usuarios
CREATE INDEX IF NOT EXISTS idx_curso_id
    ON cursos_usuarios (curso_id);

-- Índice para optimizar deleteByUsuarioId en la tabla cursos_usuarios
CREATE INDEX IF NOT EXISTS idx_usuario_id
    ON cursos_usuarios (usuario_id);

-- Índice compuesto para optimizar findByCursoIdAndUsuarioId en la tabla cursos_usuarios
CREATE UNIQUE INDEX IF NOT EXISTS idx_curso_usuario
    ON cursos_usuarios (curso_id, usuario_id);
