-- Tabla flyway
CREATE TABLE IF NOT EXISTS flyway_schema_history (
                                       installed_rank INT NOT NULL,
                                       version VARCHAR(50),
                                       description VARCHAR(200) NOT NULL,
                                       type VARCHAR(20) NOT NULL,
                                       script VARCHAR(1000) NOT NULL,
                                       checksum INT,
                                       installed_by VARCHAR(100) NOT NULL,
                                       installed_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       execution_time INT NOT NULL,
                                       success BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS cursos (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        nombre VARCHAR(255) NOT NULL,
                        PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cursos_usuarios (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                 usuario_id BIGINT UNIQUE,
                                 curso_id BIGINT REFERENCES cursos(id),
                                 PRIMARY KEY (id)
);
